kind: InternalService
name: SERVICE_NAME
spec:
  image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
  env:
  - name: ACCEPT_EULA
    value: Y
  - name: MSSQL_SA_PASSWORD
    value: STRONG_PASSWORD
    hidden: true
  port_mapping:
    - port: 1433
      target_port: 1433
  volume_mounts:
    - mount_path: "/var/opt/mssql"
      sub_path: "sqlserver"
      volume_name: VOLUME_NAME
  resources:
    memory: 2048Mi
