kind: InternalService
name: SERVICE_NAME
spec:
  image: library/mysql:5.7
  image_pull_policy: Always
  env:
   - name: MYSQL_ROOT_PASSWORD
     value: STRONG_PASSWORD
  port_mapping:
   - port: 3306
     target_port: 3306
  volume_mounts:
   - mount_path: mountPath: /var/lib/mysql
     sub_path: SUB_PATH
  resources:
    memory: 400Mi
